"""
AI Career Hub — Streamlit Frontend (orchestrator)
Thin routing layer — all page logic lives in views/.
"""

import requests
import streamlit as st
from streamlit_cookies_controller import CookieController

from api_client import API_URL, api, safe_json
from auth import page_auth
from views.dashboard import page_dashboard
from views.resumes import page_resumes
from views.cover_letter import page_cover_letter
from views.job_match import page_job_match
from views.job_tracker import page_job_tracker
from views.legal import page_legal
from views.agent import page_agent

st.set_page_config(
    page_title="AI Career Hub",
    page_icon="🚀",
    layout="wide",
    initial_sidebar_state="collapsed",
)

cookie_manager = CookieController()

# CookieController renders an invisible JS bridge iframe. Hide it and the
# Streamlit wrapper that contains it (incl. the "trouble loading" banner),
# scoped via :has() to the cookie iframe so other components and sibling
# layout are untouched — the previous "~ div" rule could hide real content.
st.html(
    "<style>"
    "iframe[title*='cookies_controller' i],"
    "iframe[title*='CookieController' i],"
    "[data-testid='stCustomComponentV1']:has(iframe[title*='cookie' i]),"
    "[data-testid='stElementContainer']:has(iframe[title*='cookie' i]),"
    ".element-container:has(iframe[title*='cookie' i]) {"
    "  display:none !important;"
    "  height:0 !important;"
    "  min-height:0 !important;"
    "  margin:0 !important;"
    "  padding:0 !important;"
    "  overflow:hidden !important;"
    "  position:absolute !important;"
    "}"
    "</style>"
)

# ─── Session State Init ───────────────────────────────────────────────────────
for key in ["token", "user", "refresh_token"]:
    if key not in st.session_state:
        st.session_state[key] = None
if "current_page" not in st.session_state:
    st.session_state["current_page"] = "📋 Dashboard"
if "disclaimer_accepted" not in st.session_state:
    st.session_state["disclaimer_accepted"] = False
if "disclaimer_never_show" not in st.session_state:
    st.session_state["disclaimer_never_show"] = False
if "active_cl_id" not in st.session_state:
    st.session_state["active_cl_id"] = None


# ─── Disclaimer Modal ────────────────────────────────────────────────────────


@st.dialog("⚠️ Terms & Disclaimer")
def show_disclaimer_modal():
    st.markdown("""
    **Please read before using AI Career Hub.**

    🤖 **AI-Generated Content**
    All outputs (cover letters, ATS scores, interview questions) are generated by AI.
    They may contain inaccuracies. **Always review before submitting to employers.**

    🛡️ **Educational Use Only**
    This platform is provided for educational and demonstration purposes.
    It is not a substitute for professional career, legal, or financial advice.
    The author accepts no liability for outcomes arising from your use of this tool.

    🔒 **Your Data**
    Resume text is stored in a hosted database (AWS RDS PostgreSQL). AI requests are sent
    to Groq's API. Do **not** upload documents with passport numbers, government
    IDs, or financial details.

    By continuing you acknowledge these terms. Full details in **📜 Legal & Info**.
    """)
    st.divider()
    col_a, col_b = st.columns(2)
    if col_a.button("✅ I Understand", use_container_width=True, type="primary"):
        st.session_state["disclaimer_accepted"] = True
        st.rerun()
    if col_b.button("🔕 Never Show Again", use_container_width=True):
        st.session_state["disclaimer_accepted"] = True
        st.session_state["disclaimer_never_show"] = True
        st.rerun()


# ─── Sidebar & Navigation ────────────────────────────────────────────────────


def sidebar():
    _pages = [
        "📋 Dashboard",
        "📄 My Resumes",
        "✉️ Cover Letter",
        "🎯 Job Match Analysis",
        "📊 Job Tracker",
        "🤖 AI Agent",
        "📜 Legal & Info",
    ]
    with st.sidebar:
        st.title("🚀 AI Career Hub")
        user = st.session_state.user or {}
        st.markdown(
            f"👤 **{user.get('full_name', 'User')}**  \n`{user.get('email', '')}`"
        )
        st.divider()
        current_idx = (
            _pages.index(st.session_state["current_page"])
            if st.session_state["current_page"] in _pages
            else 0
        )
        page = st.radio(
            "Navigation", _pages, index=current_idx, label_visibility="collapsed"
        )
        st.session_state["current_page"] = page
        st.divider()
        if st.button("🚪 Logout"):
            try:
                cookie_manager.remove("auth_token")
            except Exception:
                pass
            try:
                _headers = {}
                if st.session_state.token:
                    _headers["Authorization"] = f"Bearer {st.session_state.token}"
                # Send the refresh token so the backend revokes it server-side.
                _cookies = {}
                if st.session_state.get("refresh_token"):
                    _cookies["refresh_token"] = st.session_state["refresh_token"]
                requests.post(
                    f"{API_URL}/auth/logout",
                    headers=_headers,
                    cookies=_cookies,
                    timeout=3,
                )
            except Exception:
                pass
            st.session_state.token = None
            st.session_state.user = None
            st.session_state.refresh_token = None
            st.session_state["current_page"] = "📋 Dashboard"
            st.rerun()
    return page


# ─── Session Restore from Cookie ────────────────────────────────────────────
# CookieController.get() raises TypeError when cookies dict is None during
# the first render before browser JS has hydrated. Guard with try/except.
if not st.session_state.token:
    try:
        _cookie_token = cookie_manager.get("auth_token")
    except TypeError:
        _cookie_token = None
    if _cookie_token:
        st.session_state.token = _cookie_token
        _me = safe_json(api("get", "/auth/me"), {})
        if _me and _me.get("email"):
            st.session_state.user = _me
        else:
            try:
                cookie_manager.remove("auth_token")
            except Exception:
                pass
            st.session_state.token = None

# ─── Page Routing ────────────────────────────────────────────────────────────
if not st.session_state.token:
    # Hide the sidebar collapse toggle — no sidebar content for unauthenticated users.
    st.html(
        "<style>"
        "[data-testid='stSidebar'],"
        "[data-testid='collapsedControl'] {"
        "  display:none !important;"
        "}"
        "</style>"
    )
    page_auth(cookie_manager)
else:
    if (
        not st.session_state["disclaimer_accepted"]
        and not st.session_state["disclaimer_never_show"]
    ):
        show_disclaimer_modal()

    page = sidebar()

    if page == "📋 Dashboard":
        page_dashboard()
    elif page == "📄 My Resumes":
        page_resumes()
    elif page == "✉️ Cover Letter":
        page_cover_letter()
    elif page == "🎯 Job Match Analysis":
        page_job_match()
    elif page == "📊 Job Tracker":
        page_job_tracker()
    elif page == "🤖 AI Agent":
        page_agent()
    elif page == "📜 Legal & Info":
        page_legal()
