"""
AI Career Hub — Streamlit Frontend (orchestrator)
Thin routing layer — all page logic lives in pages/.
"""

import requests
import extra_streamlit_components as stx
import streamlit as st

from api_client import API_URL, api, safe_json
from auth import page_auth
from components import show_error, show_success
from pages.dashboard import page_dashboard
from pages.resumes import page_resumes
from pages.cover_letter import page_cover_letter
from pages.job_match import page_job_match
from pages.job_tracker import page_job_tracker
from pages.legal import page_legal

st.set_page_config(
    page_title="AI Career Hub",
    page_icon="🚀",
    layout="wide",
    initial_sidebar_state="expanded",
)

# Cookie manager — must be instantiated at module level (not in cache).
# Streamlit cannot replay widget calls from cache → CachedWidgetWarning crash.
cookie_manager = stx.CookieManager(key="careerhub_session")

# ─── Session State Init ───────────────────────────────────────────────────────
for key in ["token", "user"]:
    if key not in st.session_state:
        st.session_state[key] = None
if "current_page" not in st.session_state:
    st.session_state["current_page"] = "📋 Dashboard"
if "disclaimer_accepted" not in st.session_state:
    st.session_state["disclaimer_accepted"] = False
if "disclaimer_never_show" not in st.session_state:
    st.session_state["disclaimer_never_show"] = False
if "active_cl_id" not in st.session_state:
    st.session_state["active_cl_id"] = None


# ─── Disclaimer Modal ────────────────────────────────────────────────────────


@st.dialog("⚠️ Terms & Disclaimer")
def show_disclaimer_modal():
    st.markdown("""
    **Please read before using AI Career Hub.**

    🤖 **AI-Generated Content**
    All outputs (cover letters, ATS scores, interview questions) are generated by AI.
    They may contain inaccuracies. **Always review before submitting to employers.**

    🛡️ **Educational Use Only**
    This platform is provided for educational and demonstration purposes.
    It is not a substitute for professional career, legal, or financial advice.
    The author accepts no liability for outcomes arising from your use of this tool.

    🔒 **Your Data**
    Resume text is stored in a hosted database (Supabase). AI requests are sent
    to Groq's API. Do **not** upload documents with passport numbers, government
    IDs, or financial details.

    By continuing you acknowledge these terms. Full details in **📜 Legal & Info**.
    """)
    st.divider()
    col_a, col_b = st.columns(2)
    if col_a.button("✅ I Understand", use_container_width=True, type="primary"):
        st.session_state["disclaimer_accepted"] = True
        st.rerun()
    if col_b.button("🔕 Never Show Again", use_container_width=True):
        st.session_state["disclaimer_accepted"] = True
        st.session_state["disclaimer_never_show"] = True
        st.rerun()


# ─── Sidebar & Navigation ────────────────────────────────────────────────────


def sidebar():
    _pages = [
        "📋 Dashboard",
        "📄 My Resumes",
        "✉️ Cover Letter",
        "🎯 Job Match Analysis",
        "📊 Job Tracker",
        "📜 Legal & Info",
    ]
    with st.sidebar:
        st.title("🚀 AI Career Hub")
        user = st.session_state.user or {}
        st.markdown(
            f"👤 **{user.get('full_name', 'User')}**  \n`{user.get('email', '')}`"
        )
        st.divider()
        current_idx = (
            _pages.index(st.session_state["current_page"])
            if st.session_state["current_page"] in _pages
            else 0
        )
        page = st.radio(
            "Navigation", _pages, index=current_idx, label_visibility="collapsed"
        )
        st.session_state["current_page"] = page
        st.divider()
        if st.button("🚪 Logout"):
            cookie_manager.delete("auth_token")
            try:
                requests.post(f"{API_URL}/auth/logout", timeout=3)
            except Exception:
                pass
            st.session_state.token = None
            st.session_state.user = None
            st.session_state["current_page"] = "📋 Dashboard"
            st.rerun()
    return page


# ─── Session Restore from Cookie ────────────────────────────────────────────
if not st.session_state.token:
    _cookie_token = cookie_manager.get("auth_token")
    if _cookie_token:
        st.session_state.token = _cookie_token
        _me = safe_json(api("get", "/auth/me"), {})
        if _me and _me.get("email"):
            st.session_state.user = _me
        else:
            cookie_manager.delete("auth_token")
            st.session_state.token = None

# ─── Page Routing ────────────────────────────────────────────────────────────
if not st.session_state.token:
    page_auth(cookie_manager)
else:
    if (
        not st.session_state["disclaimer_accepted"]
        and not st.session_state["disclaimer_never_show"]
    ):
        show_disclaimer_modal()

    page = sidebar()

    if page == "📋 Dashboard":
        page_dashboard()
    elif page == "📄 My Resumes":
        page_resumes()
    elif page == "✉️ Cover Letter":
        page_cover_letter()
    elif page == "🎯 Job Match Analysis":
        page_job_match()
    elif page == "📊 Job Tracker":
        page_job_tracker()
    elif page == "📜 Legal & Info":
        page_legal()
