"""
AI Career Hub — Streamlit Frontend (orchestrator)
Thin routing layer — page logic lives in views/; navigation via st.navigation.
"""

import time

import requests
import streamlit as st
from streamlit_cookies_controller import CookieController

import tour
from api_client import API_URL, api, safe_json
from auth import page_auth
from session import cookie_get, cookie_remove
from views.agent import page_agent
from views.cover_letter import page_cover_letter
from views.dashboard import page_dashboard
from views.job_match import page_job_match
from views.job_tracker import page_job_tracker
from views.legal import page_legal
from views.resumes import page_resumes

st.set_page_config(
    page_title="AI Career Hub",
    page_icon="🚀",
    layout="wide",
    initial_sidebar_state="auto",
)

cookie_manager = CookieController()

# CookieController renders a JS bridge iframe. Move it (and its wrapper, incl.
# the "trouble loading" banner) off-screen rather than display:none — the iframe
# must stay in the layout to hydrate, or the cookie never loads and a page reload
# logs the user out. Scoped via :has() to the cookie iframe so other components
# and sibling layout are untouched.
st.html(
    "<style>"
    "iframe[title*='cookies_controller' i],"
    "iframe[title*='CookieController' i],"
    "[data-testid='stCustomComponentV1']:has(iframe[title*='cookie' i]),"
    "[data-testid='stElementContainer']:has(iframe[title*='cookie' i]),"
    ".element-container:has(iframe[title*='cookie' i]) {"
    "  position:absolute !important;"
    "  left:-9999px !important;"
    "  top:0 !important;"
    "  width:1px !important;"
    "  height:1px !important;"
    "  opacity:0 !important;"
    "  pointer-events:none !important;"
    "  overflow:hidden !important;"
    "  margin:0 !important;"
    "  padding:0 !important;"
    "  border:0 !important;"
    "}"
    "</style>"
)

# ─── Session State Init ───────────────────────────────────────────────────────
for key in ["token", "user", "refresh_token"]:
    if key not in st.session_state:
        st.session_state[key] = None
if "disclaimer_accepted" not in st.session_state:
    st.session_state["disclaimer_accepted"] = False
if "disclaimer_never_show" not in st.session_state:
    st.session_state["disclaimer_never_show"] = False
if "active_cl_id" not in st.session_state:
    st.session_state["active_cl_id"] = None


# ─── Disclaimer Modal ────────────────────────────────────────────────────────


@st.dialog("⚠️ Terms & Disclaimer")
def show_disclaimer_modal():
    st.markdown("""
    **Please read before using AI Career Hub.**

    🤖 **AI-Generated Content**
    All outputs (cover letters, ATS scores, interview questions) are generated by AI.
    They may contain inaccuracies. **Always review before submitting to employers.**

    🛡️ **Educational Use Only**
    This platform is provided for educational and demonstration purposes.
    It is not a substitute for professional career, legal, or financial advice.
    The author accepts no liability for outcomes arising from your use of this tool.

    🔒 **Your Data**
    Resume text is stored in a hosted database (AWS RDS PostgreSQL). AI requests are sent
    to Groq's API. Do **not** upload documents with passport numbers, government
    IDs, or financial details.

    By continuing you acknowledge these terms. Full details in **📜 Legal & Info**.
    """)
    st.divider()
    col_a, col_b = st.columns(2)
    if col_a.button("✅ I Understand", use_container_width=True, type="primary"):
        st.session_state["disclaimer_accepted"] = True
        st.rerun()
    if col_b.button("🔕 Never Show Again", use_container_width=True):
        st.session_state["disclaimer_accepted"] = True
        st.session_state["disclaimer_never_show"] = True
        st.rerun()


# ─── Logout ──────────────────────────────────────────────────────────────────


def _logout():
    cookie_remove(cookie_manager, "auth_token")
    try:
        _headers = {}
        if st.session_state.token:
            _headers["Authorization"] = f"Bearer {st.session_state.token}"
        # Send the refresh token so the backend revokes it server-side.
        _cookies = {}
        if st.session_state.get("refresh_token"):
            _cookies["refresh_token"] = st.session_state["refresh_token"]
        requests.post(
            f"{API_URL}/auth/logout",
            headers=_headers,
            cookies=_cookies,
            timeout=3,
        )
    except Exception:
        pass
    st.session_state.token = None
    st.session_state.user = None
    st.session_state.refresh_token = None
    st.rerun()


# ─── Session Restore from Cookie ────────────────────────────────────────────
# The cookie bridge hydrates a beat AFTER the first script run, so a reload or
# a duplicated tab must not conclude "logged out" from one empty read. Retry a
# few short runs before showing login; any hydrated token restores immediately.
# Bounded, so a genuinely signed-out visitor still sees login within ~1.5s.
_RESTORE_TRIES = 5

if not st.session_state.token:
    _cookie_token = cookie_get(cookie_manager, "auth_token")
    if _cookie_token:
        st.session_state["_restore_tries"] = _RESTORE_TRIES  # settled
        st.session_state.token = _cookie_token
        _me = safe_json(api("get", "/auth/me"), {})
        if _me and _me.get("email"):
            st.session_state.user = _me
        else:
            cookie_remove(cookie_manager, "auth_token")
            st.session_state.token = None
    else:
        _tries = st.session_state.get("_restore_tries", 0)
        if _tries < _RESTORE_TRIES:
            st.session_state["_restore_tries"] = _tries + 1
            st.caption("⏳ Restoring session…")
            time.sleep(0.3)
            st.rerun()

# ─── Page Routing ────────────────────────────────────────────────────────────
if not st.session_state.token:
    # Hide the sidebar collapse toggle — no sidebar content for unauthenticated users.
    st.html(
        "<style>"
        "[data-testid='stSidebar'],"
        "[data-testid='collapsedControl'] {"
        "  display:none !important;"
        "}"
        "</style>"
    )
    page_auth(cookie_manager)
else:
    if (
        not st.session_state["disclaimer_accepted"]
        and not st.session_state["disclaimer_never_show"]
    ):
        show_disclaimer_modal()

    # Journey-first navigation. Home and the one-shot agent lead; the manual
    # tools sit under "Workspace". Pages are URL-deep-linkable and auth-gated
    # (only registered here, after login — the login screen has no nav).
    home = st.Page(page_dashboard, title="Home", icon="🏠", default=True)
    quick_apply = st.Page(page_agent, title="Quick Apply", icon="✨", url_path="quick-apply")
    resumes = st.Page(page_resumes, title="Resumes", icon="📄", url_path="resumes")
    job_match = st.Page(page_job_match, title="Job Match", icon="🎯", url_path="job-match")
    cover_letter = st.Page(
        page_cover_letter, title="Cover Letter", icon="✉️", url_path="cover-letter"
    )
    tracker = st.Page(page_job_tracker, title="Tracker", icon="📊", url_path="tracker")
    legal = st.Page(page_legal, title="Legal & Info", icon="📜", url_path="legal")

    # Registry for cross-page navigation via st.switch_page from inside a view
    # (e.g. the dashboard quick-actions). Rebuilt every run, so never stale.
    st.session_state["_nav"] = {
        "home": home,
        "agent": quick_apply,
        "resumes": resumes,
        "job_match": job_match,
        "cover_letter": cover_letter,
        "tracker": tracker,
        "legal": legal,
    }

    nav = st.navigation(
        {
            "Start": [home, quick_apply],
            "Workspace": [resumes, job_match, cover_letter, tracker],
            "More": [legal],
        }
    )

    with st.sidebar:
        st.divider()
        _user = st.session_state.user or {}
        st.markdown(f"👤 **{_user.get('full_name', 'User')}**  \n`{_user.get('email', '')}`")
        if st.button("🧭 Product tour", use_container_width=True):
            tour.start()
        if st.button("🚪 Logout", use_container_width=True):
            _logout()

    # The tour rail draws above whatever page runs next. Resolve the active nav
    # key by identity against the registry built above — st.navigation returns
    # the same st.Page object it was handed.
    _current = next((k for k, p in st.session_state["_nav"].items() if p is nav), None)
    if _current:
        tour.render(_current)

    nav.run()
