"""PDF generation service for cover letters using reportlab."""

import io
from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.lib.pagesizes import LETTER
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer


def generate_cover_letter_pdf(cover_letter_text: str, user_name: str = "") -> bytes:
    """
    Render a cover letter as a clean, professional PDF.
    Returns raw PDF bytes ready to stream to the client.
    """
    buffer = io.BytesIO()

    doc = SimpleDocTemplate(
        buffer,
        pagesize=LETTER,
        leftMargin=1.1 * inch,
        rightMargin=1.1 * inch,
        topMargin=1.1 * inch,
        bottomMargin=1.0 * inch,
    )

    styles = getSampleStyleSheet()

    # --- Custom styles ---
    header_style = ParagraphStyle(
        "Header",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#6B7280"),  # muted gray
        alignment=TA_CENTER,
        spaceAfter=4,
    )

    date_style = ParagraphStyle(
        "Date",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#6B7280"),
        alignment=TA_LEFT,
        spaceAfter=16,
    )

    body_style = ParagraphStyle(
        "Body",
        parent=styles["Normal"],
        fontSize=11,
        leading=17,  # line height
        textColor=colors.HexColor("#1F2937"),
        alignment=TA_LEFT,
        spaceAfter=12,
    )

    # --- Build content ---
    story = []

    # Header line
    if user_name:
        story.append(Paragraph(user_name, header_style))
        story.append(Spacer(1, 4))

    today = datetime.now().strftime("%B %d, %Y")
    story.append(
        Paragraph(
            f"Generated by AI Career Hub • {today}",
            header_style,
        )
    )
    story.append(Spacer(1, 20))
    story.append(Paragraph(today, date_style))

    # Body — split on double newlines to preserve paragraph structure
    paragraphs = [p.strip() for p in cover_letter_text.split("\n\n") if p.strip()]
    for para in paragraphs:
        # Replace single newlines with spaces within a paragraph
        clean = para.replace("\n", " ")
        story.append(Paragraph(clean, body_style))

    doc.build(story)
    return buffer.getvalue()
